# fly.toml app configuration file generated for veeyds-api on 2026-07-06T10:16:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'veeyds-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOWED_ORIGINS = 'https://veeyds.vercel.app'
  API_BASE_URL = 'https://veeyds-api.fly.dev'
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
